language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - travis_retry pip install coveralls

script:
  - coverage run runtests.py

after_success:
  - coveralls